pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building the application...'
                sh 'g++ -o hello hello.cpp'
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests...'
                sh 'chmod +x hello'  // Ensure executable permission
                sh './hello'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying Application...'
            }
        }
    }
    
    post {
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check logs.'
        }
    }
}
